### ISSUE TITLE
no module named 'adafruit_ble'

### ISSUE THREAD

**Issue by lidonglei1** [adafruit/Adafruit_CircuitPython_BLE_LYWSD03MMC#10]
hello,
I used microbitV2 and esp32 with CircuitPython 9.0.3,but they all report the err：
ImportError: no module named 'adafruit_ble'
How could i install or find the adafruit_ble module ?
Thank you.

**Comment by tannewt** [comment]
This guide explains how to install libraries like `adafruit_ble`: https://learn.adafruit.com/welcome-to-circuitpython/circuitpython-libraries

**Comment by lidonglei1** [comment]
> This guide explains how to install libraries like `adafruit_ble`: https://learn.adafruit.com/welcome-to-circuitpython/circuitpython-libraries

Is BLE supported on the ESP32 in CircuitPython?
https://forums.adafruit.com/viewtopic.php?p=1011494&hilit=LYWSD03MMC#p1011494

**Comment by dhalbert** [comment]
> Is BLE supported on the ESP32 in CircuitPython?

Not yet: https://learn.adafruit.com/welcome-to-circuitpython/frequently-asked-questions#faq-3129409

Space is also limited on the ESP32 and if we add BLE we may need to remove some other things.
